on:
  push

jobs:
  update_test_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install prerequisites
        run: sudo apt-get install -y libasound2-dev libsdl2-dev

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - name: Build emulator
        run: cargo build --release
      
